"""username and free_credits

Revision ID: 6a321a8396d7
Revises: df589ce895bd
Create Date: 2025-01-31 09:22:31.205269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a321a8396d7'
down_revision: Union[str, None] = 'df589ce895bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('free_credits_left', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_credits_left')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
