"""free_credits -> credts

Revision ID: c06c4b04a4df
Revises: 17b6a1a0d548
Create Date: 2025-02-01 14:49:46.223750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06c4b04a4df'
down_revision: Union[str, None] = '17b6a1a0d548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits_left', sa.Integer(), nullable=True))
    op.drop_column('users', 'free_credits_left')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_credits_left', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'credits_left')
    # ### end Alembic commands ###
